---
version: '3'
services:
    build_war:
        build:
            context: ./docker
            dockerfile: WarBuild.Dockerfile
        volumes:
            - 'app:/tmp/'

    mysql_srv:
        image: mysql:5.6.51
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: qQ123456
            MYSQL_DATABASE: db
        ports:
            - '3306:3306'

    dep_war: 
        image: tomcat:alpine
        volumes:
            - 'app:/usr/local/tomcat/webapps/'
            - './docker/config:/usr/local/tomcat/ROOT/'
        depends_on: 
            - build_war
            - mysql_srv
        ports:
            - '8080:8080'

volumes:
    app: